export const MAX_EMAIL_CHARACTERS = 60;
export const MIN_PASSWORD_CHARACTERS = 8;
export const MAX_PASSWORD_CHARACTERS = 60;

export const MAX_VAULT_GROUP_CHARACTERS = 20;
export const MIN_VAULT_GROUP_CHARACTERS = 1;
